#ifndef BTT_TFT35_E3_BOARD_CLOCK_H
#define BTT_TFT35_E3_BOARD_CLOCK_H

enum
{
  DISPLAY_SYSTEM_CORE_CLOCK_HZ = 120000000,
  DISPLAY_SYSTEM_CORE_CLOCK_MHZ = 120,
  DISPLAY_APB1_PERIPHERAL_CLOCK_HZ = DISPLAY_SYSTEM_CORE_CLOCK_HZ / 2u,
  DISPLAY_SYSTICK_RELOAD_TICKS = DISPLAY_SYSTEM_CORE_CLOCK_HZ / 1000u,
};

#endif // BTT_TFT35_E3_BOARD_CLOCK_H
